project:
  title: "Posit Documentation"
  type: posit-docs
  
website:
  sidebar:
    contents:
      - text: "Introduction"
        href: index.qmd
      - text: "Page 1"
        href: index.qmd
  page-footer:
    left: |
      Copyright &copy; 2000-{{< env CURRENT_YEAR >}} Posit Software, PBC. All Rights Reserved.
    center: |
      Posit PRODUCT {{< env PRODUCT_VERSION >}}
    right:
      - icon: question-circle-fill
        href: "https://support.posit.co/hc/en-us"
      - icon: lightbulb-fill
        href: "https://solutions.posit.co/"
      - text: "<img src='/_extensions/posit-docs/assets/images/posit-guide-ltmd.svg' id='footer-right-logo'>"
        href: "https://docs.posit.co/"
      - text: "<img src='/_extensions/posit-docs/assets/images/posit-logo-black-TM.svg' id='footer-right-posit-logo'>"
        href: "https://posit.co/"

format:
  posit-docs-html:
    toc: true
