project:
  type: posit-docs
  
website:
  title: 'Posit Product Documentation <small>Version {{< env PRODUCT_VERSION >}}</small>'
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Admin Guide"
        file: admin.qmd
      - text: "User Guide"
        file: user.qmd

  # Hybrid navigation meant to show some amount of nested sidebar navigation
  # https://quarto.org/docs/websites/website-navigation.html#hybrid-navigation
  sidebar:
    - title: "Admin Guide"
      contents:
        - admin.qmd
        - section: Subsection
          contents:
            - text: Installation
              file: install.qmd
            - text: Duplicate
              file: install.qmd

    - title: "User Guide"
      contents:
        - user.qmd
        - section: Subsection
          contents:
            - text: Sharing
              file: sharing.qmd
            - text: Duplicate
              file: sharing.qmd

  page-footer:
    left: |
      Copyright &copy; 2000-{{< env CURRENT_YEAR >}} Posit Software, PBC. All Rights Reserved.
    center: |
      Posit PRODUCT {{< env PRODUCT_VERSION >}}
    right:
      - icon: question-circle-fill
        href: "https://support.posit.co/hc/en-us"
      - icon: lightbulb-fill
        href: "https://solutions.posit.co/"
      - text: "<img src='/_extensions/posit-docs/assets/images/posit-guide-ltmd.svg' id='footer-right-logo'>"
        href: "https://docs.posit.co/"
      - text: "<img src='/_extensions/posit-docs/assets/images/posit-icon-fullcolor.svg' id='footer-right-posit-logo'>"
        href: "https://posit.co/"
